# Generated by Django 5.0 on 2025-10-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
