# Generated by Django 5.0 on 2025-10-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0002_alter_staffmodel_email_alter_staffmodel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, null=True),
        ),
    ]
