# Generated by Django 6.0.2 on 2026-02-10 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0002_departmentmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='human_resource.departmentmodel')),
            ],
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_staffs', to='human_resource.positionmodel'),
        ),
        migrations.AddConstraint(
            model_name='positionmodel',
            constraint=models.UniqueConstraint(fields=('name', 'department'), name='unique_dept_name_and_dept_combo'),
        ),
    ]
