# Generated by Django 5.0 on 2025-10-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_alter_staffmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
