# Generated by Django 6.0.2 on 2026-02-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_positionmodel_staffmodel_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='category',
            field=models.CharField(blank=True, choices=[('TEACHING', 'TEACHING'), ('NON TEACHING', 'NON TEACHING')], max_length=20, null=True),
        ),
    ]
