# Generated by Django 6.0.2 on 2026-03-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0004_staffmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/staff_images'),
        ),
    ]
