# Generated by Django 5.0 on 2025-10-24 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0005_staffuploadtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffWalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_wallet', to='human_resource.staffmodel')),
            ],
        ),
    ]
