# Generated by Django 5.0 on 2025-09-22 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_site', '0004_termmodel_alter_activitylogmodel_term_and_more'),
        ('finance', '0001_initial'),
        ('human_resource', '0001_initial'),
        ('inventory', '0001_initial'),
        ('student', '0006_alter_fingerprintmodel_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advancesettlementmodel',
            name='advance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='inventory.purchaseadvancemodel'),
        ),
        migrations.AddField(
            model_name='advancesettlementmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecategorymodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.expensecategorymodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='feegroupmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feegroupmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fee_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_masters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='finance.feegroupmodel'),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='student_class',
            field=models.ManyToManyField(blank=True, help_text='Select classes this fee applies to.', to='admin_site.classesmodel'),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fee_masters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feemodel',
            name='payment_term',
            field=models.ForeignKey(blank=True, help_text="For 'One Time' fees, specify which term it must be paid in.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='feemodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='finance.feemodel'),
        ),
        migrations.AddField(
            model_name='feepaymentmodel',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feepaymentmodel',
            name='fee_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.feemastermodel'),
        ),
        migrations.AddField(
            model_name='feepaymentmodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='feepaymentmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='student.studentmodel'),
        ),
        migrations.AddField(
            model_name='feepaymentmodel',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='financesettingmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomecategorymodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.incomecategorymodel'),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='purchaseadvancepaymentmodel',
            name='advance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.purchaseadvancemodel'),
        ),
        migrations.AddField(
            model_name='purchaseadvancepaymentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryadvancemodel',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryadvancemodel',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_salary_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryadvancemodel',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='staffbankdetail',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who recorded this funding transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_list', to='student.studentmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='purchase_orders',
            field=models.ManyToManyField(blank=True, to='inventory.purchaseordermodel'),
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.suppliermodel'),
        ),
        migrations.AddConstraint(
            model_name='feemastermodel',
            constraint=models.UniqueConstraint(fields=('fee', 'group'), name='unique_fee_master_combo'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('staff', 'month', 'year')},
        ),
    ]
