# Generated by Django 5.0 on 2025-12-19 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_site', '0002_initial'),
        ('finance', '0001_initial'),
        ('human_resource', '0001_initial'),
        ('inventory', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advancesettlementmodel',
            name='advance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='inventory.purchaseadvancemodel'),
        ),
        migrations.AddField(
            model_name='advancesettlementmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountapplicationmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountapplicationmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='discountapplicationmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='discountmodel',
            name='applicable_classes',
            field=models.ManyToManyField(blank=True, help_text='Classes this discount can apply to.', related_name='applicable_classes', to='admin_site.classesmodel'),
        ),
        migrations.AddField(
            model_name='discountmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountapplicationmodel',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='finance.discountmodel'),
        ),
        migrations.AddField(
            model_name='expensecategorymodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorised_expenses', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategorymodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_expenses', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_expenses', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='feegroupmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='class_sections',
            field=models.ManyToManyField(blank=True, help_text='Optional: narrow down to specific sections (e.g., JSS1 A).', to='admin_site.classsectionmodel'),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='finance.feegroupmodel'),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='student_classes',
            field=models.ManyToManyField(help_text='Select all classes this fee structure applies to.', to='admin_site.classesmodel'),
        ),
        migrations.AddField(
            model_name='feemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feemodel',
            name='payment_term',
            field=models.ForeignKey(blank=True, help_text="For 'One Time' fees, specify which term it must be paid in.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='feemodel',
            name='required_utility',
            field=models.ForeignKey(blank=True, help_text='If set, this fee is only applied to students subscribed to this utility (e.g., Bus Fee for Transport Utility).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.utilitymodel'),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='finance.feemodel'),
        ),
        migrations.AddField(
            model_name='discountmodel',
            name='applicable_fees',
            field=models.ManyToManyField(blank=True, help_text='Fees this discount can be applied against.', to='finance.feemodel'),
        ),
        migrations.AddField(
            model_name='feepaymentmodel',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financesettingmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomecategorymodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='finance.incomecategorymodel'),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='invoicegenerationjob',
            name='classes_to_invoice',
            field=models.ManyToManyField(to='admin_site.classesmodel'),
        ),
        migrations.AddField(
            model_name='invoicegenerationjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicegenerationjob',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='invoicegenerationjob',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='fee_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.feemastermodel'),
        ),
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='paid_by_sibling',
            field=models.ForeignKey(blank=True, help_text='If this is a parent-bound fee paid by a sibling', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_fees_covered', to='student.studentmodel'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='student.studentmodel'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoicemodel'),
        ),
        migrations.AddField(
            model_name='feepaymentmodel',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.invoicemodel'),
        ),
        migrations.AddField(
            model_name='otherpaymentclearancemodel',
            name='confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_other_clearances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherpaymentmodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_other_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otherpaymentmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='otherpaymentmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other_debts', to='student.studentmodel'),
        ),
        migrations.AddField(
            model_name='otherpaymentmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='otherpaymentclearancemodel',
            name='other_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearances', to='finance.otherpaymentmodel'),
        ),
        migrations.AddField(
            model_name='purchaseadvancepaymentmodel',
            name='advance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='inventory.purchaseadvancemodel'),
        ),
        migrations.AddField(
            model_name='purchaseadvancepaymentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_salaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='salaryrecordhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrecordhistory',
            name='salary_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='finance.salaryrecord'),
        ),
        migrations.AddField(
            model_name='salarysetting',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='salary_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to='finance.salarysetting'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='salary_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_structures', to='finance.salarysetting'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='salary_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_records', to='finance.salarystructure'),
        ),
        migrations.AddField(
            model_name='otherpaymentclearancemodel',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.schoolbankdetail'),
        ),
        migrations.AddField(
            model_name='feepaymentmodel',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.schoolbankdetail'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.schoolbankdetail'),
        ),
        migrations.AddField(
            model_name='staffbankdetail',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='stafffundingmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who recorded this funding transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='stafffundingmodel',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_staff_fundings', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='stafffundingmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='stafffundingmodel',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_funding_list', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='stafffundingmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='staffloan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_staff_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffloan',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='staffloan',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_loans', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='staffloan',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='staffloanrepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffloanrepayment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='staffloanrepayment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_repayments', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='staffloanrepayment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='studentdiscountmodel',
            name='discount_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_discounts', to='finance.discountapplicationmodel'),
        ),
        migrations.AddField(
            model_name='studentdiscountmodel',
            name='invoice_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts_applied', to='finance.invoiceitemmodel'),
        ),
        migrations.AddField(
            model_name='studentdiscountmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts_received', to='student.studentmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who recorded this funding transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_fundings', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_list', to='student.studentmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='purchase_orders',
            field=models.ManyToManyField(blank=True, to='inventory.purchaseordermodel'),
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.suppliermodel'),
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='termlyfeeamountmodel',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termly_amounts', to='finance.feemastermodel'),
        ),
        migrations.AddField(
            model_name='termlyfeeamountmodel',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_site.termmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='discountapplicationmodel',
            unique_together={('discount', 'session', 'term')},
        ),
        migrations.AddIndex(
            model_name='expensecategorymodel',
            index=models.Index(fields=['is_active'], name='finance_exp_is_acti_a213e1_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategorymodel',
            index=models.Index(fields=['name'], name='finance_exp_name_7edd95_idx'),
        ),
        migrations.AddConstraint(
            model_name='feemastermodel',
            constraint=models.UniqueConstraint(fields=('fee', 'group'), name='unique_fee_master_combo'),
        ),
        migrations.AddIndex(
            model_name='incomecategorymodel',
            index=models.Index(fields=['is_active'], name='finance_inc_is_acti_b98728_idx'),
        ),
        migrations.AddIndex(
            model_name='incomecategorymodel',
            index=models.Index(fields=['name'], name='finance_inc_name_af2541_idx'),
        ),
        migrations.AddIndex(
            model_name='incomemodel',
            index=models.Index(fields=['income_date'], name='finance_inc_income__bbf0d8_idx'),
        ),
        migrations.AddIndex(
            model_name='incomemodel',
            index=models.Index(fields=['category'], name='finance_inc_categor_1434e3_idx'),
        ),
        migrations.AddIndex(
            model_name='incomemodel',
            index=models.Index(fields=['session'], name='finance_inc_session_7d8bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='incomemodel',
            index=models.Index(fields=['term'], name='finance_inc_term_id_9f06fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicemodel',
            unique_together={('student', 'session', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('staff', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='expensemodel',
            index=models.Index(fields=['expense_date'], name='finance_exp_expense_81af3f_idx'),
        ),
        migrations.AddIndex(
            model_name='expensemodel',
            index=models.Index(fields=['category'], name='finance_exp_categor_1a8d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='expensemodel',
            index=models.Index(fields=['session'], name='finance_exp_session_fb9100_idx'),
        ),
        migrations.AddIndex(
            model_name='expensemodel',
            index=models.Index(fields=['term'], name='finance_exp_term_id_08fa06_idx'),
        ),
        migrations.AddIndex(
            model_name='expensemodel',
            index=models.Index(fields=['voucher_number'], name='finance_exp_voucher_a65afe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentdiscountmodel',
            unique_together={('student', 'discount_application', 'invoice_item')},
        ),
        migrations.AlterUniqueTogether(
            name='termlyfeeamountmodel',
            unique_together={('fee_structure', 'term')},
        ),
    ]
