# Generated by Django 5.0 on 2025-09-23 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_termmodel_alter_activitylogmodel_term_and_more'),
        ('finance', '0002_initial'),
        ('inventory', '0003_alter_itemmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierpaymentmodel',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': 'Supplier Payment', 'verbose_name_plural': 'Supplier Payments'},
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('reverted', 'Reverted')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierpaymentmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AlterField(
            model_name='supplierpaymentmodel',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], default='bank_transfer', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierpaymentmodel',
            name='reference',
            field=models.CharField(blank=True, help_text='e.g., Cheque number, transaction ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplierpaymentmodel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='inventory.suppliermodel'),
        ),
    ]
