# Generated by Django 5.0 on 2025-12-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarysetting',
            name='allowances',
            field=models.JSONField(blank=True, default=list, help_text='Additional allowances configuration'),
        ),
        migrations.AlterField(
            model_name='salarysetting',
            name='income_items',
            field=models.JSONField(blank=True, default=list, help_text='Additional income items to display on payslip'),
        ),
        migrations.AlterField(
            model_name='salarysetting',
            name='reliefs_exemptions',
            field=models.JSONField(blank=True, default=list, help_text='Tax reliefs and exemptions configuration'),
        ),
        migrations.AlterField(
            model_name='salarysetting',
            name='statutory_deductions',
            field=models.JSONField(blank=True, default=list, help_text='Statutory deductions like Pension, NHF'),
        ),
    ]
