# Generated by Django 5.0 on 2025-09-24 07:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_termmodel_alter_activitylogmodel_term_and_more'),
        ('finance', '0003_alter_supplierpaymentmodel_options_and_more'),
        ('human_resource', '0001_initial'),
        ('student', '0006_alter_fingerprintmodel_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceGenerationJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=20)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('processed_students', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
            ],
            options={
                'verbose_name': 'Student Invoice',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermlyFeeAmountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['term__order'],
            },
        ),
        migrations.RemoveField(
            model_name='salaryadvancemodel',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='salaryadvancemodel',
            name='disbursed_by',
        ),
        migrations.RemoveField(
            model_name='salaryadvancemodel',
            name='staff',
        ),
        migrations.AlterModelOptions(
            name='expensecategorymodel',
            options={'ordering': ('name',), 'verbose_name': 'Expense Category', 'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='expensemodel',
            options={'ordering': ('-expense_date', '-created_at'), 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='feegroupmodel',
            options={'ordering': ['name'], 'verbose_name': 'Fee Group'},
        ),
        migrations.AlterModelOptions(
            name='feemodel',
            options={'ordering': ['name'], 'verbose_name': 'Fee Type'},
        ),
        migrations.AlterModelOptions(
            name='feepaymentmodel',
            options={'ordering': ['-date'], 'verbose_name': 'Fee Payment'},
        ),
        migrations.AlterModelOptions(
            name='incomecategorymodel',
            options={'ordering': ('name',), 'verbose_name': 'Income Category', 'verbose_name_plural': 'Income Categories'},
        ),
        migrations.AlterModelOptions(
            name='incomemodel',
            options={'ordering': ('-income_date', '-created_at'), 'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
        migrations.AlterModelOptions(
            name='salaryrecord',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterModelOptions(
            name='salarystructure',
            options={'verbose_name': 'Salary Structure'},
        ),
        migrations.AlterModelOptions(
            name='staffbankdetail',
            options={'verbose_name': 'Staff Bank Detail'},
        ),
        migrations.RemoveField(
            model_name='feegroupmodel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='feemastermodel',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='feemastermodel',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='feemastermodel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='feemodel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='feepaymentmodel',
            name='fee_master',
        ),
        migrations.RemoveField(
            model_name='feepaymentmodel',
            name='payment_proof',
        ),
        migrations.RemoveField(
            model_name='feepaymentmodel',
            name='session',
        ),
        migrations.RemoveField(
            model_name='feepaymentmodel',
            name='student',
        ),
        migrations.RemoveField(
            model_name='feepaymentmodel',
            name='term',
        ),
        migrations.RemoveField(
            model_name='staffbankdetail',
            name='sort_code',
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='class_sections',
            field=models.ManyToManyField(blank=True, help_text='Optional: narrow down to specific sections (e.g., JSS1 A).', to='admin_site.classsectionmodel'),
        ),
        migrations.AddField(
            model_name='feemastermodel',
            name='student_classes',
            field=models.ManyToManyField(help_text='Select all classes this fee structure applies to.', to='admin_site.classesmodel'),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='incomemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='salaryrecord',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategorymodel'),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='expense_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Bank Transfer')], default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='finance/expenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='admin_site.sessionmodel'),
        ),
        migrations.AlterField(
            model_name='feemastermodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feemastermodel',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structures', to='finance.feemodel'),
        ),
        migrations.AlterField(
            model_name='feemastermodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='finance.feegroupmodel'),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='incomemodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='incomemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='finance.incomecategorymodel'),
        ),
        migrations.AlterField(
            model_name='incomemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incomes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incomemodel',
            name='income_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incomemodel',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='finance/income/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='incomemodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='admin_site.sessionmodel'),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='e.g., salary advance repayment', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='human_resource.staffmodel'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='pension_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage (e.g., 8)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage (e.g., 7.5)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='staffbankdetail',
            name='account_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='expensecategorymodel',
            index=models.Index(fields=['is_active'], name='finance_exp_is_acti_a213e1_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategorymodel',
            index=models.Index(fields=['name'], name='finance_exp_name_7edd95_idx'),
        ),
        migrations.AddIndex(
            model_name='expensemodel',
            index=models.Index(fields=['expense_date'], name='finance_exp_expense_81af3f_idx'),
        ),
        migrations.AddIndex(
            model_name='expensemodel',
            index=models.Index(fields=['category'], name='finance_exp_categor_1a8d4d_idx'),
        ),
        migrations.AddIndex(
            model_name='expensemodel',
            index=models.Index(fields=['session'], name='finance_exp_session_fb9100_idx'),
        ),
        migrations.AddIndex(
            model_name='expensemodel',
            index=models.Index(fields=['term'], name='finance_exp_term_id_08fa06_idx'),
        ),
        migrations.AddIndex(
            model_name='incomecategorymodel',
            index=models.Index(fields=['is_active'], name='finance_inc_is_acti_b98728_idx'),
        ),
        migrations.AddIndex(
            model_name='incomecategorymodel',
            index=models.Index(fields=['name'], name='finance_inc_name_af2541_idx'),
        ),
        migrations.AddIndex(
            model_name='incomemodel',
            index=models.Index(fields=['income_date'], name='finance_inc_income__bbf0d8_idx'),
        ),
        migrations.AddIndex(
            model_name='incomemodel',
            index=models.Index(fields=['category'], name='finance_inc_categor_1434e3_idx'),
        ),
        migrations.AddIndex(
            model_name='incomemodel',
            index=models.Index(fields=['session'], name='finance_inc_session_7d8bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='incomemodel',
            index=models.Index(fields=['term'], name='finance_inc_term_id_9f06fa_idx'),
        ),
        migrations.AddField(
            model_name='invoicegenerationjob',
            name='classes_to_invoice',
            field=models.ManyToManyField(to='admin_site.classesmodel'),
        ),
        migrations.AddField(
            model_name='invoicegenerationjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicegenerationjob',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='invoicegenerationjob',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='fee_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.feemastermodel'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='student.studentmodel'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoicemodel'),
        ),
        migrations.AddField(
            model_name='feepaymentmodel',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.invoicemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='termlyfeeamountmodel',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termly_amounts', to='finance.feemastermodel'),
        ),
        migrations.AddField(
            model_name='termlyfeeamountmodel',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_site.termmodel'),
        ),
        migrations.DeleteModel(
            name='SalaryAdvanceModel',
        ),
        migrations.AlterUniqueTogether(
            name='invoicemodel',
            unique_together={('student', 'session', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='termlyfeeamountmodel',
            unique_together={('fee_structure', 'term')},
        ),
    ]
