# Generated by Django 5.0 on 2025-12-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_salarysetting_allowances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('bank_teller', 'Bank Teller'), ('pos', 'POS'), ('dollar_pay', 'Dollar Pay'), ('others', 'OTHERS')], max_length=20),
        ),
    ]
