# Generated by Django 5.0 on 2026-01-15 16:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_feepaymentmodel_payment_mode'),
        ('human_resource', '0002_departmentmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('staff', 'Staff'), ('volunteer', 'Volunteer')], default='staff', help_text='Select whether this bonus is for a staff member or volunteer', max_length=10)),
                ('category', models.CharField(choices=[('vol_corp', 'Vol. Corp'), ('contractors', 'Contractors'), ('staff_monthly', 'Staff Monthly Bonus'), ('transportation', 'Transportation'), ('others', 'Others')], default='others', help_text='Select the category of this bonus', max_length=20)),
                ('volunteer_name', models.CharField(blank=True, help_text="Enter volunteer name if type is 'Volunteer'", max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Bonus amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('month', models.PositiveIntegerField(editable=False, help_text='Month extracted from due date (1-12)')),
                ('year', models.PositiveIntegerField(editable=False, help_text='Year extracted from due date')),
                ('due_date', models.DateField(default=django.utils.timezone.now, help_text='Due date for payment (month and year will be extracted from this)')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', help_text='Payment status', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this bonus', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bonuses', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(blank=True, help_text="Select staff member if type is 'Staff'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='human_resource.staffmodel')),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuses',
                'ordering': ['-year', '-month', '-created_at'],
                'indexes': [models.Index(fields=['year', 'month'], name='finance_bon_year_a2b68f_idx'), models.Index(fields=['type'], name='finance_bon_type_80c50d_idx'), models.Index(fields=['category'], name='finance_bon_categor_3ca3f1_idx'), models.Index(fields=['status'], name='finance_bon_status_04e779_idx')],
            },
        ),
    ]
