# Generated by Django 5.0 on 2025-09-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_salaryadvance_repaid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensemodel',
            name='description',
        ),
    ]
