# Generated by Django 5.0 on 2026-01-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystructure',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Bank code from NUBAN API', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='beneficiary_code',
            field=models.CharField(blank=True, help_text='Beneficiary code for bank transfer', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='branch_sort_code',
            field=models.CharField(blank=True, help_text='Branch sort code', max_length=20, null=True),
        ),
    ]
