# Generated by Django 5.0 on 2026-01-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_salarystructure_bank_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='collected_by_other',
            field=models.CharField(blank=True, help_text='Name of non-staff collector (if not selecting from staff list)', max_length=200, null=True),
        ),
    ]
