# Generated by Django 5.0 on 2025-09-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_expensemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomemodel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
