# Generated by Django 5.0 on 2026-01-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_expensemodel_collected_by_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfundingmodel',
            name='wallet_type',
            field=models.CharField(choices=[('canteen', 'Canteen Wallet'), ('fee', 'Fee Wallet')], default='canteen', help_text='Which wallet this funding is for', max_length=20),
        ),
    ]
