# Generated by Django 5.0 on 2025-09-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_incomemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfundingmodel',
            name='mode',
            field=models.CharField(blank=True, choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=100),
        ),
    ]
