# Generated by Django 5.0 on 2026-01-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_studentfundingmodel_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('bank_teller', 'Bank Teller'), ('pos', 'POS'), ('wallet', 'Fee Wallet'), ('dollar_pay', 'Dollar Pay'), ('others', 'OTHERS')], max_length=20),
        ),
    ]
