# Generated by Django 5.0 on 2025-09-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_studentfundingmodel_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='fee',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
