# Generated by Django 5.0 on 2025-09-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_invoicemodel_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemodel',
            name='fee',
        ),
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
