# Generated by Django 5.0 on 2026-01-28 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_feepaymentmodel_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.schoolbankdetail'),
        ),
    ]
