# Generated by Django 5.0 on 2025-09-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_invoicemodel_fee_invoiceitemmodel_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
