# Generated by Django 5.0 on 2026-01-30 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_feepaymentmodel_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomemodel',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='finance.schoolbankdetail'),
        ),
    ]
