# Generated by Django 5.0 on 2025-10-11 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_schoolbankdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepaymentmodel',
            name='bank_account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='finance.schoolbankdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feemodel',
            name='occurrence',
            field=models.CharField(choices=[('quaterly', 'Quaterly'), ('annually', 'Annually'), ('one_time', 'One Time')], max_length=50),
        ),
    ]
