# Generated by Django 6.0.2 on 2026-03-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_incomemodel_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepaymentmodel',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='parent_proofs/'),
        ),
    ]
