# Generated by Django 6.0.2 on 2026-03-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_feepaymentmodel_proof_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reverted', 'Reverted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
