# Generated by Django 6.0.2 on 2026-03-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_feepaymentmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomemodel',
            name='currency',
            field=models.CharField(choices=[('naira', 'Naira (NGN)'), ('dollar', 'Dollar (USD)')], default='naira', max_length=20),
        ),
    ]
