# Generated by Django 6.0.2 on 2026-04-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_incomemodel_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='additional_field_values',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of additional field values (e.g., Rent) used for this payslip'),
        ),
        migrations.AddField(
            model_name='salarysetting',
            name='additional_fields',
            field=models.JSONField(blank=True, default=list, help_text='Extra fields for staff salary profile (e.g., Rent for relief calculation)'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='additional_field_values',
            field=models.JSONField(blank=True, default=dict, help_text='Values for the extra fields defined in SalarySetting'),
        ),
    ]
