# Generated by Django 5.0 on 2025-10-30 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_classesmodel_code'),
        ('finance', '0015_staffloan_staffloanrepayment_and_more'),
        ('human_resource', '0006_staffwalletmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffFundingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='images/funding')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('pos', 'POS'), ('bank teller', 'Bank Teller'), ('bank transfer', 'Bank Transfer')], default='cash', max_length=100)),
                ('mode', models.CharField(blank=True, choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='confirmed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teller_number', models.CharField(blank=True, max_length=50, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('reference', models.CharField(blank=True, help_text='Unique reference for this transaction.', max_length=250, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who recorded this funding transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_funding_list', to='human_resource.staffmodel')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel')),
            ],
            options={
                'verbose_name': 'Student Funding Record',
                'verbose_name_plural': 'Student Funding Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
