# Generated by Django 5.0 on 2025-11-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_stafffundingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('bank_teller', 'Bank Teller')], max_length=20),
        ),
    ]
