# Generated by Django 6.0.4 on 2026-05-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_salaryrecord_additional_field_values_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], help_text='Payment gateway provider.', max_length=20, unique=True)),
                ('display_name', models.CharField(help_text='Label shown to parents/staff on the payment page.', max_length=100)),
                ('public_key', models.TextField(help_text='Public/publishable key from the gateway dashboard.')),
                ('_secret_key', models.TextField(db_column='secret_key', help_text='Secret key — stored encrypted.')),
                ('_webhook_secret', models.TextField(db_column='webhook_secret', help_text='Webhook secret/hash — stored encrypted.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active gateways appear on the payment page.')),
                ('is_test_mode', models.BooleanField(default=False, help_text='When enabled, test keys are expected and payments are not real.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'ordering': ['gateway'],
            },
        ),
    ]
