# Generated by Django 5.0 on 2025-11-14 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_feepaymentmodel_payment_mode'),
        ('student', '0012_studentmodel_utilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='feemodel',
            name='parent_bound',
            field=models.BooleanField(default=False, help_text='Check if this fee should be charged once per Parent/Family, rather than per student.'),
        ),
        migrations.AddField(
            model_name='feemodel',
            name='required_utility',
            field=models.ForeignKey(blank=True, help_text='If set, this fee is only applied to students subscribed to this utility (e.g., Bus Fee for Transport Utility).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.utilitymodel'),
        ),
    ]
