# Generated by Django 6.0.4 on 2026-05-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_paymentgatewaymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('bank_teller', 'Bank Teller'), ('pos', 'POS'), ('wallet', 'Fee Wallet'), ('dollar_pay', 'Dollar Pay'), ('online', 'Online Payment'), ('others', 'OTHERS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stafffundingmodel',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('pos', 'POS'), ('bank teller', 'Bank Teller'), ('bank transfer', 'Bank Transfer'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='cash', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentfundingmodel',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('pos', 'POS'), ('bank teller', 'Bank Teller'), ('bank transfer', 'Bank Transfer'), ('paystack', 'Paystack'), ('flutterwave', 'Flutterwave')], default='cash', max_length=100),
        ),
    ]
