# Generated by Django 6.0.4 on 2026-06-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_feepaymentmodel_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystructure',
            name='component_overrides',
            field=models.JSONField(blank=True, default=dict, help_text="Manual overrides for allowances/reliefs. Format: {'allowances': {'Housing Allowance': 75000.0}, 'reliefs': {'Personal Relief': 200000.0}}"),
        ),
    ]
