# Generated by Django 5.0 on 2025-11-14 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_feemodel_parent_bound_feemodel_required_utility'),
        ('student', '0012_studentmodel_utilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitemmodel',
            name='paid_by_sibling',
            field=models.ForeignKey(blank=True, help_text='If this is a parent-bound fee paid by a sibling', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_fees_covered', to='student.studentmodel'),
        ),
    ]
