# Generated by Django 5.0 on 2025-11-14 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_classesmodel_code'),
        ('finance', '0019_invoiceitemmodel_paid_by_sibling'),
        ('student', '0012_studentmodel_utilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Staff Discount, Early Bird Discount', max_length=250, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount ($)')], help_text='The intended type for this discount blueprint.', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Default value (amount/percentage) for initial application setup.', max_digits=10, null=True)),
                ('occurrence', models.CharField(choices=[('quaterly', 'Quaterly'), ('annually', 'Annually'), ('one_time', 'One Time (Single Term)')], max_length=50)),
                ('is_protected', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_classes', models.ManyToManyField(blank=True, help_text='Classes this discount can apply to.', related_name='applicable_classes', to='admin_site.classesmodel')),
                ('applicable_fees', models.ManyToManyField(blank=True, help_text='Fees this discount can be applied against.', to='finance.feemodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discount Blueprint',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DiscountApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount ($)')], help_text='The type of discount (Percentage or Fixed) locked for this term.', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='The exact amount or percentage locked for this term.', max_digits=10)),
                ('is_protected', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_site.sessionmodel')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_site.termmodel')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='finance.discountmodel')),
            ],
            options={
                'verbose_name': 'Discount Application',
                'ordering': ['-session__id', 'term__order'],
                'unique_together': {('discount', 'session', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentDiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_discounted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_discounts', to='finance.discountapplicationmodel')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts_applied', to='finance.invoicemodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts_received', to='student.studentmodel')),
            ],
            options={
                'verbose_name': 'Student Discount Record',
                'unique_together': {('student', 'discount_application', 'invoice')},
            },
        ),
    ]
