# Generated by Django 5.0 on 2025-11-18 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_fix_studentdiscount_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdiscountmodel',
            name='invoice_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts_applied', to='finance.invoiceitemmodel'),
        ),
    ]
