# Generated by Django 5.0 on 2025-11-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_expensemodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepaymentmodel',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('bank_teller', 'Bank Teller'), ('dollar_pay', 'Dollar Pay'), ('others', 'OTHERS')], max_length=20),
        ),
    ]
