# Generated by Django 5.0 on 2025-11-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_feepaymentmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepaymentmodel',
            name='currency',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='naira', max_length=20),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='payment_mode',
            field=models.CharField(choices=[('naira', 'Naira (NGN)'), ('dollar', 'Dollar (USD)')], max_length=20),
        ),
    ]
