# Generated by Django 5.0 on 2025-11-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_feepaymentmodel_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='currency',
            field=models.CharField(choices=[('naira', 'Naira (NGN)'), ('dollar', 'Dollar (USD)')], default='naira', max_length=20),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('bank_teller', 'Bank Teller'), ('dollar_pay', 'Dollar Pay'), ('others', 'OTHERS')], max_length=20),
        ),
    ]
