# Generated by Django 5.0 on 2025-11-21 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_classesmodel_code'),
        ('finance', '0025_alter_feepaymentmodel_currency_and_more'),
        ('human_resource', '0006_staffwalletmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expensemodel',
            name='authorised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorised_expenses', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.schoolbankdetail'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='cheque_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='cheque_prepared_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='cheque_signed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_expenses', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='currency',
            field=models.CharField(choices=[('naira', 'Naira (NGN)'), ('dollar', 'Dollar (USD)')], default='naira', max_length=20),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='line_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_expenses', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='vote_and_subhead',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='voucher_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Bank Transfer'), ('dollar_pay', 'Dollar Pay'), ('others', 'Others')], default='cash', max_length=50),
        ),
        migrations.AddIndex(
            model_name='expensemodel',
            index=models.Index(fields=['voucher_number'], name='finance_exp_voucher_a65afe_idx'),
        ),
    ]
