# Generated by Django 5.0 on 2025-11-25 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_expensemodel_authorised_by_expensemodel_bank_account_and_more'),
        ('human_resource', '0006_staffwalletmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafffundingmodel',
            name='refund_reason',
            field=models.CharField(blank=True, help_text='Reason for revert/refund.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stafffundingmodel',
            name='reverted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafffundingmodel',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_staff_fundings', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='refund_reason',
            field=models.CharField(blank=True, help_text='Reason for revert/refund.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='reverted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfundingmodel',
            name='reverted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_fundings', to='human_resource.staffmodel'),
        ),
        migrations.AlterField(
            model_name='stafffundingmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reverted', 'Reverted')], default='confirmed', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentfundingmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reverted', 'Reverted')], default='confirmed', max_length=30),
        ),
    ]
