# Generated by Django 5.0 on 2025-12-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_stafffundingmodel_refund_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepaymentmodel',
            name='item_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Stores breakdown of payment across invoice items'),
        ),
        migrations.AlterField(
            model_name='feepaymentmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reverted', 'Reverted')], default='pending', max_length=20),
        ),
    ]
