# Generated by Django 5.0 on 2025-12-18 07:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_classesmodel_code'),
        ('finance', '0028_feepaymentmodel_item_breakdown_and_more'),
        ('student', '0012_studentmodel_utilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Brief description of the debt/charge', max_length=500)),
                ('category', models.CharField(choices=[('historical', 'Historical Debt'), ('fine', 'Fine/Penalty'), ('damage', 'Damage Fee'), ('other', 'Other')], default='historical', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount owed', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid so far', max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('currency', models.CharField(choices=[('naira', 'Naira (₦)'), ('dollar', 'Dollar ($)')], default='naira', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or context', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_other_payments', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other_debts', to='student.studentmodel')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel')),
            ],
            options={
                'verbose_name': 'Other Payment/Debt',
                'verbose_name_plural': 'Other Payments/Debts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtherPaymentClearanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('bank_teller', 'Bank Teller'), ('dollar_pay', 'Dollar Pay'), ('others', 'Others')], max_length=20)),
                ('currency', models.CharField(choices=[('naira', 'Naira (₦)'), ('dollar', 'Dollar ($)')], default='naira', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('reverted', 'Reverted')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.schoolbankdetail')),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_other_clearances', to=settings.AUTH_USER_MODEL)),
                ('other_payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clearances', to='finance.otherpaymentmodel')),
            ],
            options={
                'verbose_name': 'Other Payment Clearance',
                'verbose_name_plural': 'Other Payment Clearances',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
