# Generated by Django 5.0 on 2026-02-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmodel',
            options={'ordering': ['name'], 'permissions': [('view_inventory_report', 'Can view inventory reports')], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
    ]
