# Generated by Django 5.0 on 2025-09-23 06:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_termmodel_alter_activitylogmodel_term_and_more'),
        ('inventory', '0002_alter_suppliermodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemmodel',
            options={'ordering': ['name'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderitemmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseordermodel',
            options={'ordering': ['-order_date', '-created_at'], 'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.RemoveField(
            model_name='purchaseorderitemmodel',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='purchaseordermodel',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='purchaseordermodel',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseordermodel',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='purchaseordermodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.categorymodel'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='current_selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('pack', 'Pack'), ('box', 'Box'), ('kg', 'Kilogram'), ('carton', 'Carton')], default='piece', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorderitemmodel',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemmodel'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitemmodel',
            name='item_description',
            field=models.CharField(help_text='Auto-filled if an inventory item is selected, or enter a custom description.', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorderitemmodel',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseordermodel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.suppliermodel'),
        ),
        migrations.AddConstraint(
            model_name='itemmodel',
            constraint=models.UniqueConstraint(fields=('name', 'unit'), name='unique_item_name_unit'),
        ),
    ]
