# Generated by Django 5.0 on 2025-09-23 08:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_itemmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockinmodel',
            options={'ordering': ['-date_received'], 'verbose_name': 'Stock In Batch'},
        ),
        migrations.RemoveField(
            model_name='stockinmodel',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='stockinmodel',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='stockinmodel',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stockinmodel',
            name='quantity_received',
        ),
        migrations.RemoveField(
            model_name='stockinmodel',
            name='quantity_remaining',
        ),
        migrations.RemoveField(
            model_name='stockinmodel',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='stockinmodel',
            name='unit_cost',
        ),
        migrations.AddField(
            model_name='purchaseorderitemmodel',
            name='is_stocked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockinmodel',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stockinmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockinmodel',
            name='location',
            field=models.CharField(choices=[('shop', 'Shop Only'), ('store', 'Store Only'), ('both', 'Both Shop & Store')], default='store', max_length=10),
        ),
        migrations.CreateModel(
            name='StockInItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='inventory.itemmodel')),
                ('purchase_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseorderitemmodel')),
                ('stock_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockinmodel')),
            ],
        ),
    ]
