# Generated by Django 5.0 on 2025-09-23 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockinmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockoutmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='stockoutmodel',
            name='sale',
        ),
        migrations.AlterField(
            model_name='stockoutmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stk_out_cb', to=settings.AUTH_USER_MODEL),
        ),
    ]
