# Generated by Django 5.0 on 2025-09-23 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
        ('inventory', '0005_remove_stockoutmodel_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockoutmodel',
            options={'ordering': ['-date_removed'], 'verbose_name': 'Stock Out Record'},
        ),
        migrations.RemoveField(
            model_name='stockoutmodel',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='stockoutmodel',
            name='reference',
        ),
        migrations.AlterField(
            model_name='stockoutmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='inventory.itemmodel'),
        ),
        migrations.AlterField(
            model_name='stockoutmodel',
            name='location',
            field=models.CharField(choices=[('store', 'Store'), ('shop', 'Shop')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stockoutmodel',
            name='reason',
            field=models.CharField(choices=[('staff_collection', 'Staff Collection'), ('damage', 'Damage'), ('expired', 'Expired'), ('adjustment', 'Stock Adjustment'), ('wastage', 'Wastage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockoutmodel',
            name='staff_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
    ]
