# Generated by Django 5.0 on 2025-09-23 17:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_termmodel_alter_activitylogmodel_term_and_more'),
        ('inventory', '0007_stockinmodel_session_stockinmodel_term_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffitemrequestmodel',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='staffitemrequestmodel',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='staffitemrequestmodel',
            name='staff',
        ),
        migrations.AlterModelOptions(
            name='stocktransfermodel',
            options={'ordering': ['-transfer_date', '-created_at'], 'verbose_name': 'Stock Transfer Batch'},
        ),
        migrations.RemoveField(
            model_name='stocktransfermodel',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stocktransfermodel',
            name='quantity',
        ),
        migrations.AddField(
            model_name='stocktransfermodel',
            name='direction',
            field=models.CharField(choices=[('store_to_shop', 'Store to Shop'), ('shop_to_store', 'Shop to Store')], default='shop_to_store', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransfermodel',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='stocktransfermodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='stocktransfermodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.CreateModel(
            name='StockTransferItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemmodel')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='StaffItemRequestItemModel',
        ),
        migrations.DeleteModel(
            name='StaffItemRequestModel',
        ),
    ]
