# Generated by Django 5.0 on 2025-09-23 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_stocktransfermodel_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransferitemmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory.itemmodel'),
        ),
    ]
