# Generated by Django 5.0 on 2025-09-23 20:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_termmodel_alter_activitylogmodel_term_and_more'),
        ('inventory', '0010_alter_stocktransferitemmodel_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseadvancemodel',
            options={'ordering': ['-request_date', '-created_at'], 'verbose_name': 'Purchase Advance', 'verbose_name_plural': 'Purchase Advances'},
        ),
        migrations.AddField(
            model_name='purchaseadvancemodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseadvancemodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='purchaseadvancemodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AlterField(
            model_name='purchaseadvancemodel',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
