# Generated by Django 5.0 on 2025-09-24 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_termmodel_alter_activitylogmodel_term_and_more'),
        ('inventory', '0011_alter_purchaseadvancemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salemodel',
            options={'ordering': ['-sale_date'], 'verbose_name': 'Sale Transaction'},
        ),
        migrations.RemoveField(
            model_name='saleitemmodel',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='saleitemmodel',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='salemodel',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='salemodel',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='salemodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AlterField(
            model_name='saleitemmodel',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemmodel'),
        ),
        migrations.AlterField(
            model_name='saleitemmodel',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='The selling price at the time of sale.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('student_wallet', 'Student Wallet'), ('pos', 'POS')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('refunded', 'Refunded')], default='completed', max_length=20),
        ),
    ]
