# Generated by Django 5.0 on 2025-10-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_salemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockoutmodel',
            name='reason',
            field=models.CharField(choices=[('staff_collection', 'Staff Collection'), ('damage', 'Damage'), ('expired', 'Expired'), ('adjustment', 'Stock Adjustment'), ('wastage', 'Wastage'), ('cafeteria', 'Cafeteria'), ('boarding house store', 'Boarding House Store')], max_length=20),
        ),
    ]
