# Generated by Django 5.0 on 2025-10-12 12:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_termmodel_alter_activitylogmodel_term_and_more'),
        ('human_resource', '0004_alter_staffmodel_mobile'),
        ('inventory', '0014_alter_inventoryassignmentmodel_term_and_more'),
        ('student', '0007_importbatchmodel_parentmodel_excel_pid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectSaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_completed', models.BooleanField(default=True)),
                ('payment_method', models.CharField(blank=True, help_text='Cash, Transfer, etc.', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sale_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_sales', to='inventory.itemmodel')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel')),
                ('sold_by', models.ForeignKey(blank=True, help_text='Staff who processed the sale', null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_purchases', to='student.studentmodel')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel')),
            ],
            options={
                'verbose_name': 'Direct Sale',
                'verbose_name_plural': 'Direct Sales',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
    ]
