# Generated by Django 5.0 on 2025-10-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_directsalemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='location',
            field=models.CharField(choices=[('shop', 'Tuck Shop Only'), ('store', 'Store Only'), ('both', 'Both Tuck Shop & Store')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockinmodel',
            name='location',
            field=models.CharField(choices=[('shop', 'Tuck Shop Only'), ('store', 'Store Only'), ('both', 'Both Tuck Shop & Store')], default='store', max_length=10),
        ),
        migrations.AlterField(
            model_name='stocktransfermodel',
            name='direction',
            field=models.CharField(choices=[('store_to_shop', 'Store to Tuck Shop'), ('shop_to_store', 'Shop to Store')], max_length=20),
        ),
    ]
