# Generated by Django 5.0 on 2025-11-02 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0006_staffwalletmodel'),
        ('inventory', '0016_alter_itemmodel_location_alter_stockinmodel_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemodel',
            name='staff_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='human_resource.staffmodel'),
        ),
        migrations.AlterField(
            model_name='salemodel',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('student_wallet', 'Student Wallet'), ('staff_wallet', 'Staff Wallet'), ('pos', 'POS')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='stocktransfermodel',
            name='direction',
            field=models.CharField(choices=[('store_to_shop', 'Store to Tuck Shop'), ('shop_to_store', 'Tuck Shop to Store')], max_length=20),
        ),
    ]
