# Generated by Django 5.0 on 2025-11-19 17:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_classesmodel_code'),
        ('human_resource', '0006_staffwalletmodel'),
        ('inventory', '0017_salemodel_staff_customer_and_more'),
        ('student', '0012_studentmodel_utilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoutmodel',
            name='department',
            field=models.CharField(blank=True, choices=[('cleaning', 'Cleaning and Sanitation'), ('drivers', 'Drivers'), ('clinic', 'Clinic'), ('admin', 'Admin'), ('cafeteria', 'Cafeteria'), ('maintenance', 'Maintenance')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ClassInventoryCollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_collected', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_inventory_collections', to='admin_site.classesmodel')),
                ('collected_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemmodel')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel')),
                ('student_representative', models.ForeignKey(blank=True, help_text='Student who came to collect the item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentmodel')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel')),
            ],
            options={
                'verbose_name': 'Class Inventory Collection',
                'ordering': ['-date_collected'],
            },
        ),
    ]
