# Generated by Django 5.0 on 2025-11-19 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0005_classesmodel_code'),
        ('inventory', '0018_stockoutmodel_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinventorycollectionmodel',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_section_collections', to='admin_site.classsectionmodel'),
        ),
    ]
