# Generated by Django 5.0 on 2025-09-22 06:00

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_meals_per_day', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealCollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(default=django.utils.timezone.now)),
                ('collection_time', models.TimeField(auto_now_add=True)),
                ('fee_charged', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount charged for this meal (if any)', max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Meal Collection',
                'verbose_name_plural': 'Meal Collections',
                'ordering': ['-collection_date', '-collection_time'],
            },
        ),
        migrations.CreateModel(
            name='MealModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
