# Generated by Django 5.0 on 2025-12-19 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_meals_per_day', models.PositiveIntegerField(default=3, help_text='The maximum number of meals a student can collect in a single day.')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable the entire cafeteria meal collection system.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cafeteria Setting',
                'verbose_name_plural': 'Cafeteria Settings',
            },
        ),
        migrations.CreateModel(
            name='MealCollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(default=django.utils.timezone.now)),
                ('collection_time', models.TimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Meal Collection Record',
                'ordering': ['-collection_date', '-collection_time'],
            },
        ),
        migrations.CreateModel(
            name='MealModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
