# Generated by Django 5.0 on 2025-12-19 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_site', '0002_initial'),
        ('cafeteria', '0002_initial'),
        ('human_resource', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcollectionmodel',
            name='served_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='mealcollectionmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='mealcollectionmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_collections', to='student.studentmodel'),
        ),
        migrations.AddField(
            model_name='mealcollectionmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AddField(
            model_name='mealmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealcollectionmodel',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafeteria.mealmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='mealcollectionmodel',
            unique_together={('student', 'meal', 'collection_date')},
        ),
    ]
