# Generated by Django 5.0 on 2025-09-24 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_initial'),
        ('finance', '0003_alter_supplierpaymentmodel_options_and_more'),
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafeteriasettingmodel',
            options={'verbose_name': 'Cafeteria Setting', 'verbose_name_plural': 'Cafeteria Settings'},
        ),
        migrations.AlterModelOptions(
            name='mealcollectionmodel',
            options={'ordering': ['-collection_date', '-collection_time'], 'verbose_name': 'Meal Collection Record'},
        ),
        migrations.RemoveField(
            model_name='cafeteriasettingmodel',
            name='session',
        ),
        migrations.RemoveField(
            model_name='cafeteriasettingmodel',
            name='term',
        ),
        migrations.RemoveField(
            model_name='mealcollectionmodel',
            name='fee_charged',
        ),
        migrations.AlterField(
            model_name='cafeteriasettingmodel',
            name='cafeteria_fee',
            field=models.ForeignKey(blank=True, help_text='Select the fee that grants students access to the cafeteria.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.feemodel'),
        ),
        migrations.AlterField(
            model_name='cafeteriasettingmodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable or disable the entire cafeteria meal collection system.'),
        ),
        migrations.AlterField(
            model_name='cafeteriasettingmodel',
            name='max_meals_per_day',
            field=models.PositiveIntegerField(default=3, help_text='The maximum number of meals a student can collect in a single day.'),
        ),
        migrations.AlterField(
            model_name='mealcollectionmodel',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafeteria.mealmodel'),
        ),
        migrations.AlterField(
            model_name='mealcollectionmodel',
            name='served_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
    ]
