# Generated by Django 5.0 on 2025-12-19 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_site', '0001_initial'),
        ('human_resource', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentIDGeneratorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentIDGeneratorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_generate_student_id', models.BooleanField(default=True)),
                ('student_prefix', models.CharField(blank=True, default='STU', max_length=10, null=True)),
                ('auto_generate_parent_id', models.BooleanField(default=True)),
                ('parent_prefix', models.CharField(blank=True, default='PAR', max_length=10, null=True)),
                ('max_fingerprints_per_student', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the utility (e.g., Boarding, Transport)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Unique code for this utility (e.g., BRD, TRN)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utility',
                'verbose_name_plural': 'Utilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('parent_file_name', models.CharField(max_length=255)),
                ('student_file_name', models.CharField(max_length=255)),
                ('parents_created', models.IntegerField(default=0)),
                ('parents_updated', models.IntegerField(default=0)),
                ('students_created', models.IntegerField(default=0)),
                ('students_updated', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
            ],
            options={
                'verbose_name': 'Import Batch',
                'verbose_name_plural': 'Import Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('parent_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('excel_pid', models.CharField(blank=True, db_index=True, help_text='PID from Excel import file', max_length=50, null=True)),
                ('import_batch_id', models.CharField(blank=True, db_index=True, help_text='Unique identifier for import batch', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('residential_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['excel_pid', 'import_batch_id'], name='student_par_excel_p_4cb078_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParentProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_password', models.CharField(max_length=100)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to='student.parentmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/student_images')),
                ('import_batch_id', models.CharField(blank=True, db_index=True, help_text='Unique identifier for import batch', max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('graduated', 'GRADUATED'), ('suspended', 'SUSPENDED'), ('inactive', 'INACTIVE')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.classsectionmodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='student.parentmodel')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.classesmodel')),
                ('utilities', models.ManyToManyField(blank=True, help_text='Services the student is subscribed to (e.g., Transport, Boarding)', related_name='students', to='student.utilitymodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentWalletModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_wallet', to='student.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='FingerprintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger_name', models.CharField(choices=[('LEFT_THUMB', 'Left Thumb'), ('LEFT_INDEX', 'Left Index'), ('LEFT_MIDDLE', 'Left Middle'), ('LEFT_RING', 'Left Ring'), ('LEFT_LITTLE', 'Left Little'), ('RIGHT_THUMB', 'Right Thumb'), ('RIGHT_INDEX', 'Right Index'), ('RIGHT_MIDDLE', 'Right Middle'), ('RIGHT_RING', 'Right Ring'), ('RIGHT_LITTLE', 'Right Little')], max_length=20)),
                ('fingerprint_template', models.TextField(help_text='Base64 encoded fingerprint template')),
                ('quality_score', models.FloatField(blank=True, help_text='Fingerprint quality (0.0-1.0)', null=True)),
                ('capture_device', models.CharField(blank=True, default='U.are.U 4500', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fingerprints', to='student.studentmodel')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'is_active'], name='student_fin_student_2926e2_idx'), models.Index(fields=['created_at'], name='student_fin_created_a46f9e_idx')],
                'unique_together': {('student', 'finger_name')},
            },
        ),
        migrations.AddIndex(
            model_name='studentmodel',
            index=models.Index(fields=['first_name', 'last_name', 'parent'], name='student_stu_first_n_5217f7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmodel',
            index=models.Index(fields=['import_batch_id'], name='student_stu_import__dd08e5_idx'),
        ),
    ]
