# Generated by Django 5.0 on 2025-09-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentmodel',
            name='gender',
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parentmodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
