# Generated by Django 5.0 on 2025-09-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_parentmodel_gender_alter_parentmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
