# Generated by Django 6.0.2 on 2026-03-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentwalletmodel_fee_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprintmodel',
            name='enrolled_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
