# Generated by Django 5.0 on 2025-09-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_parentmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentmodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
