# Generated by Django 5.0 on 2025-09-21 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_parentmodel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wards', to='student.parentmodel'),
        ),
    ]
