# Generated by Django 5.0 on 2025-09-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentmodel_parent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fingerprintmodel',
            unique_together={('student', 'finger_name')},
        ),
        migrations.AddField(
            model_name='fingerprintmodel',
            name='capture_device',
            field=models.CharField(blank=True, default='U.are.U 4500', max_length=100),
        ),
        migrations.AddField(
            model_name='fingerprintmodel',
            name='fingerprint_template',
            field=models.TextField(default='ll', help_text='Base64 encoded fingerprint template'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fingerprintmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fingerprintmodel',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprintmodel',
            name='quality_score',
            field=models.FloatField(blank=True, help_text='Fingerprint quality (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='fingerprintmodel',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fingerprintmodel',
            name='finger_name',
            field=models.CharField(choices=[('LEFT_THUMB', 'Left Thumb'), ('LEFT_INDEX', 'Left Index'), ('LEFT_MIDDLE', 'Left Middle'), ('LEFT_RING', 'Left Ring'), ('LEFT_LITTLE', 'Left Little'), ('RIGHT_THUMB', 'Right Thumb'), ('RIGHT_INDEX', 'Right Index'), ('RIGHT_MIDDLE', 'Right Middle'), ('RIGHT_RING', 'Right Ring'), ('RIGHT_LITTLE', 'Right Little')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='fingerprintmodel',
            index=models.Index(fields=['student', 'is_active'], name='student_fin_student_2926e2_idx'),
        ),
        migrations.AddIndex(
            model_name='fingerprintmodel',
            index=models.Index(fields=['created_at'], name='student_fin_created_a46f9e_idx'),
        ),
        migrations.RemoveField(
            model_name='fingerprintmodel',
            name='fingerprint_data',
        ),
    ]
