# Generated by Django 5.0 on 2025-10-11 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_termmodel_alter_activitylogmodel_term_and_more'),
        ('human_resource', '0004_alter_staffmodel_mobile'),
        ('student', '0006_alter_fingerprintmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('parent_file_name', models.CharField(max_length=255)),
                ('student_file_name', models.CharField(max_length=255)),
                ('parents_created', models.IntegerField(default=0)),
                ('parents_updated', models.IntegerField(default=0)),
                ('students_created', models.IntegerField(default=0)),
                ('students_updated', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Import Batch',
                'verbose_name_plural': 'Import Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='parentmodel',
            name='excel_pid',
            field=models.CharField(blank=True, db_index=True, help_text='PID from Excel import file', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentmodel',
            name='import_batch_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique identifier for import batch', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='import_batch_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique identifier for import batch', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.classsectionmodel'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.classesmodel'),
        ),
        migrations.AddIndex(
            model_name='parentmodel',
            index=models.Index(fields=['excel_pid', 'import_batch_id'], name='student_par_excel_p_4cb078_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmodel',
            index=models.Index(fields=['first_name', 'last_name', 'parent'], name='student_stu_first_n_5217f7_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmodel',
            index=models.Index(fields=['import_batch_id'], name='student_stu_import__dd08e5_idx'),
        ),
        migrations.AddField(
            model_name='importbatchmodel',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
    ]
