# Generated by Django 5.0 on 2025-11-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_importbatchmodel_parentmodel_excel_pid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsettingmodel',
            name='max_fingerprints_per_student',
            field=models.IntegerField(default=4),
        ),
    ]
