# Generated by Django 5.0 on 2025-11-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentsettingmodel_max_fingerprints_per_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprintmodel',
            name='extraction_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata about feature extraction'),
        ),
        migrations.AddField(
            model_name='fingerprintmodel',
            name='feature_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of fingerprint features', max_length=64),
        ),
        migrations.AddField(
            model_name='fingerprintmodel',
            name='template_version',
            field=models.CharField(default='v2', help_text='Template format version', max_length=10),
        ),
    ]
