# Generated by Django 5.0 on 2025-11-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_fingerprintmodel_extraction_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprintmodel',
            name='extraction_metadata',
        ),
        migrations.RemoveField(
            model_name='fingerprintmodel',
            name='feature_hash',
        ),
        migrations.RemoveField(
            model_name='fingerprintmodel',
            name='template_version',
        ),
    ]
