# Generated by Django 5.0 on 2025-11-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_utilitymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='utilities',
            field=models.ManyToManyField(blank=True, help_text='Services the student is subscribed to (e.g., Transport, Boarding)', related_name='students', to='student.utilitymodel'),
        ),
    ]
