# Generated by Django 5.0 on 2025-09-20 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_site', '0001_initial'),
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='form_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'group__name': 'Teachers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_teacher_rosters', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_site.classesmodel'),
        ),
        migrations.AddConstraint(
            model_name='classsectionmodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_class_name_type_combo'),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_site.classsectionmodel'),
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='section',
            field=models.ManyToManyField(blank=True, to='admin_site.classsectionmodel'),
        ),
        migrations.AddField(
            model_name='schoolsettingmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddField(
            model_name='activitylogmodel',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Session of activity.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.sessionmodel'),
        ),
        migrations.AddConstraint(
            model_name='classsectioninfomodel',
            constraint=models.UniqueConstraint(fields=('student_class', 'section'), name='unique_student_class_section_combo'),
        ),
        migrations.AddConstraint(
            model_name='classesmodel',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name_class_type_combo'),
        ),
    ]
