# Generated by Django 6.0.4 on 2026-05-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettingmodel',
            name='auto_confirm_online_payment',
            field=models.BooleanField(default=True, help_text='Automatically confirm and credit online payments on webhook receipt. If disabled, online payments go to pending for manual review.'),
        ),
        migrations.AddField(
            model_name='schoolsettingmodel',
            name='online_payment_enabled',
            field=models.BooleanField(default=True, help_text='Master switch — disables the online payment option on all pages without touching gateway configuration.'),
        ),
    ]
