# Generated by Django 5.0 on 2025-09-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsettingmodel',
            name='meal_cost',
        ),
    ]
