# Generated by Django 6.0.4 on 2026-06-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_schoolsettingmodel_auto_confirm_online_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmodel',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
