# Generated by Django 5.0 on 2025-09-21 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_remove_schoolsettingmodel_meal_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('order', models.PositiveIntegerField(help_text='Order for sorting terms (e.g., 1 for 1st Term).', unique=True)),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='activitylogmodel',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Session of activity.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
        migrations.AlterField(
            model_name='schoolsettingmodel',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_site.termmodel'),
        ),
    ]
