# Generated by Django 5.0 on 2025-10-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_termmodel_alter_activitylogmodel_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmodel',
            name='code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
